apiVersion: v1
kind: Pod
metadata:
  name: sample-pvc-dynamic-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:1.16
    volumeMounts: 
    - name: nginx-pvc
      mountPath: "/usr/share/nginx/html"
  volumes:
  - name: nginx-pvc
    persistentVolumeClaim:
      claimName: sample-pvc-dynamic


