apiVersion: v1
kind: Pod
metadata:
  name: sample-pvc-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:1.16
    volumeMounts:
    - name: nginx-pvc
      mountPath: "/usr/share/nginx/html"
    - name: nginx-pvc-2
      mountPath: "/test"
  volumes:
  - name: nginx-pvc
    persistentVolumeClaim:
      claimName: sample-pvc
  - name: nginx-pvc-2
    persistentVolumeClaim:
      claimName: sample-pvc-2