apiVersion: v1
kind: PersistentVolume
metadata: 
  name: sample-pv-2
  labels: 
    type: gce-pv
    environment: stg
spec:
  capacity: 
    storage: 10Gi
  accessModes:  
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual2
  gcePersistentDisk:
    pdName: sample-gce-pv-2
    fsType: ext4